name: CI workflow

on: 
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
    outputs:
      artifact:
        value: ${{ jobs.build_test_and_publish.artifact }}
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        type: string

env:
  PROJECT_NAME: OneClickSubscribeApi

jobs:
  build_test_and_publish:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:  
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./projects/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj --configuration Release --no-build -o ./${{ env.PROJECT_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ./${{ env.PROJECT_NAME }}.zip

      - name: Output artifact location
        if: ${{ github.event_name == 'workflow_call' }}
        id: outputArtifact
        run: echo "artifact=${{ env.PROJECT_NAME }}" >> $GITHUB_OUTPUT