name: IAC Deploy workflow

on: 
  push:
    branches:
      - main
      - develop
    paths:
      - 'templates/**'
  workflow_dispatch:

env:
  TEMPLATES_DIR: ./templates

jobs:
  deploy_iac:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'develop' }}
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.7'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{ "clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}" }'

      - name: Terraform Init
        working-directory: ${{ env.TEMPLATES_DIR }}
        run: |
          terraform init \
            -backend-config="use_azuread_auth=true" \
            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.TFSTATE_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate" 
            
      - name: Terraform Workspace Select  ${{ github.ref_name }}
        working-directory: ${{ env.TEMPLATES_DIR }}
        run: |
          terraform workspace select ${{ github.ref_name }} || terraform workspace new  ${{ github.ref_name }}

      - name: Terraform Plan
        working-directory: ${{ env.TEMPLATES_DIR }}
        run: |
          terraform plan \
          -var='env=${{ vars.ENV }}' \
          -var='org_infix=${{ vars.ORG_INFIX }}' \
          -var='app_infix=${{ vars.APP_INFIX }}' \
          -var='resource_group_name=${{ vars.RESOURCE_GROUP_NAME }}' \
          -var='function_app_name=${{ vars.FUNCTION_APP_NAME }}' \
          -var='redirect_to_form_url=${{ vars.REDIRECT_TO_FORM_URL }}' \
          -var='redirect_to_subscribed_url=${{ vars.REDIRECT_TO_SUBSCRIBED_URL }}' \
          -var='subscription_default_type=${{ vars.SUBSCRIPTION_DEFAULT_TYPE }}' \
          -var='subscription_valid_types=${{ vars.SUBSCRIPTION_VALID_TYPES }}' \
          -var='mailchimp_base_url=${{ vars.MAILCHIMP_BASE_URL }}' \
          -var='mailchimp_api_key=${{ secrets.MAILCHIMP_API_KEY }}' \
          -var='mailchimp_audience_id=${{ vars.MAILCHIMP_AUDIENCE_ID }}' \
          -var='mailchimp_type_merge_tag=${{ vars.MAILCHIMP_TYPE_MERGE_TAG }}'

      - name: Terraform Apply
        working-directory: ${{ env.TEMPLATES_DIR }}
        run: |
          terraform apply \
          -auto-approve \
          -var='env=${{ vars.ENV }}' \
          -var='org_infix=${{ vars.ORG_INFIX }}' \
          -var='app_infix=${{ vars.APP_INFIX }}' \
          -var='resource_group_name=${{ vars.RESOURCE_GROUP_NAME }}' \
          -var='function_app_name=${{ vars.FUNCTION_APP_NAME }}' \
          -var='redirect_to_form_url=${{ vars.REDIRECT_TO_FORM_URL }}' \
          -var='redirect_to_subscribed_url=${{ vars.REDIRECT_TO_SUBSCRIBED_URL }}' \
          -var='subscription_default_type=${{ vars.SUBSCRIPTION_DEFAULT_TYPE }}' \
          -var='subscription_valid_types=${{ vars.SUBSCRIPTION_VALID_TYPES }}' \
          -var='mailchimp_base_url=${{ vars.MAILCHIMP_BASE_URL }}' \
          -var='mailchimp_api_key=${{ secrets.MAILCHIMP_API_KEY }}' \
          -var='mailchimp_audience_id=${{ vars.MAILCHIMP_AUDIENCE_ID }}' \
          -var='mailchimp_type_merge_tag=${{ vars.MAILCHIMP_TYPE_MERGE_TAG }}'